const domesticCitties = [
    "Azimpur",
    "Badarganj",
    "Bagerhat",
    "Baniachang",
    "Barisāl",
    "Bera",
    "Bhairab Bāzār",
    "Bherāmāra",
    "Bhola",
    "Bhāndāria",
    "Bhātpāra Abhaynagar",
    "Bibir Hat",
    "Bogra",
    "Burhānuddin",
    "Bājitpur",
    "Bāndarban",
    "Char Bhadrāsan",
    "Char Golora",
    "Chhāgalnāiya",
    "Chhātak",
    "Chilmāri",
    "Chittagong",
    "Comilla",
    "Cox’s Bāzār",
    "Dhaka",
    "Dinājpur",
    "Dohār",
    "Farīdpur",
    "Feni",
    "Gafargaon",
    "Gaibandha",
    "Gaurnadi",
    "Habiganj",
    "Hājīganj",
    "Ishurdi",
    "Jahedpur",
    "Jamālpur",
    "Jessore",
    "Jhingergācha",
    "Joymontop",
    "Joypur Hāt",
    "Kesabpur",
    "Khagrachhari",
    "Khanbaniara",
    "Khulna",
    "Kishorganj",
    "Kushtia",
    "Kālia",
    "Kālīganj",
    "Lakshmīpur",
    "Lalmonirhat",
    "Lākshām",
    "Lālmohan",
    "Magura",
    "Mahasthangarh",
    "Manikchari",
    "Mathba",
    "Maulavi Bāzār",
    "Mehendiganj",
    "Mirzāpur",
    "Morrelgonj",
    "Muktāgācha",
    "Mymensingh",
    "Mādārīpur",
    "Nabīnagar",
    "Nageswari",
    "Narail",
    "Narsingdi",
    "Natore",
    "Nawābganj",
    "Netrakona",
    "Nowlamary",
    "Nāgarpur",
    "Nālchiti",
    "Nārāyanganj",
    "Paltan",
    "Panchagarh",
    "Parbatipur",
    "Parvez Ali Family",
    "Parvez Ali Hossain",
    "Patiya",
    "Phultala",
    "Pirojpur",
    "Purbadhala",
    "Puthia",
    "Pābna",
    "Pālang",
    "Pār Naogaon",
    "Pīrgaaj",
    "Ramnagar",
    "Rangpur",
    "Raojān",
    "Rāipur",
    "Rājshāhi",
    "Rāmganj",
    "Saidpur",
    "Sakhipur",
    "Sandwīp",
    "Sarankhola",
    "Sarishābāri",
    "Sayani",
    "Sherpur",
    "Shibganj",
    "Shibganj",
    "Shāhzādpur",
    "Sirajganj",
    "Sonārgaon",
    "Sylhet",
    "Sātkania",
    "Sātkhira",
    "Teknāf",
    "Thākurgaon",
    "Tungi",
    "Tungipāra",
    "Tāngāil",
    "Uttar Char Fasson"
]

const domesticCityList = document.getElementById('domestic-locations');

domesticCitties.forEach(city => {
    const option = document.createElement('option');
    option.value = city;
    domesticCityList.appendChild(option);
});
